# fly.toml app configuration file generated for betconverter-frontend on 2025-03-15T00:14:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'betconverter-frontend'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3010
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
